### ISSUE TITLE
Add ability to extract text from  scanned pdfs

### ISSUE THREAD

**Issue by Tsippaduida** [skvark/Textractor#9]
Scanners often create pdf-documents when you use them for copying. It would be real handy if the text in those pdfs would be available.

**Comment by skvark** [comment]
This will require some conversion library which converts pdf to image. I'll look into it.

**Comment by skvark** [comment]
This has been now implemented. Some PDF files might not work. However, that can't be fixed at Textractor side.

**Comment by Tsippaduida** [comment]
Thanks,

This is great news. Textractor in one of the best OCR engines available.

19.09.2015, 18:17, Olli-Pekka Heinisuo kirjoitti:
